name: "E2E test"
on: [push, workflow_dispatch]

# End to end tests require content permissions to create releases
# This essentially gives permissions to make ANY change in the repository, so we should not grant this to PRs
# This is an open issue for Github, see https://github.com/orgs/community/discussions/68252

jobs:
  test: # make sure the action works on a clean machine without building
    name: E2E test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Make draft
      id: make-draft
      uses: ./
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: README.md
        asset_name: TEST.md
        tag: ci-test-${{ matrix.os }}-${{ github.run_id }}
        draft: true
        body: "rofl lol test%0Aianal %25 fubar"

    - name: Assert draft release get be retrieved
      uses: actions/github-script@v7
      env:
        RELEASE_ID: ${{ steps.make-draft.outputs.release_id }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const assert = require('assert').strict;

          // We cannot find drafts by tag
          try {
            const release = await github.rest.repos.getReleaseByTag({
              ...context.repo,
              tag: "ci-test-${{ matrix.os }}-${{ github.run_id }}"
            })
          } catch (error) {
            assert.equal(error.status, 404)
          }
          
          // Instead we can find them by ID
          const release = await github.request('GET /repos/{owner}/{repo}/releases/{release_id}', {
            ...context.repo,
            release_id: process.env.RELEASE_ID,
          })
          
          assert.deepStrictEqual(release.data.draft, true)
          assert.deepStrictEqual(release.data.body, "rofl lol test\nianal % fubar")
          assert.deepStrictEqual(release.data.assets[0].name, "TEST.md")

    - name: Add files to existing draft
      uses: ./
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: README.md
        asset_name: TEST2.md
        draft: true
        release_id: ${{ steps.make-draft.outputs.release_id }}
        tag: ci-test-${{ matrix.os }}-${{ github.run_id }}

    - name: Check that files can be uploaded to existing draft
      uses: actions/github-script@v7
      env:
        RELEASE_ID: ${{ steps.make-draft.outputs.release_id }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const assert = require('assert').strict;
          
          const release = await github.request('GET /repos/{owner}/{repo}/releases/{release_id}', {
            ...context.repo,
            release_id: process.env.RELEASE_ID,
          })
          
          assert.deepStrictEqual(release.data.assets.map(a => a.name), ["TEST.md", "TEST2.md"])


    - name: Clean up draft
      if: ${{ always() }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.repos.deleteRelease({
            ...context.repo,
            release_id: ${{ steps.make-draft.outputs.release_id }},
          })

    - name: Make test pre-release
      uses: ./
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: README.md
        asset_name: TEST.md
        tag: ci-test-${{ matrix.os }}-${{ github.run_id }}
        overwrite: true
        prerelease: true
        make_latest: true
        body: "rofl lol test%0Aianal %25 fubar"

    - name: Check that the uploaded asset is readable
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs')
          const assert = require('assert').strict;

          const expected = fs.readFileSync("README.md", "utf8")
          const release = await github.rest.repos.getReleaseByTag({
            ...context.repo,
            tag: "ci-test-${{ matrix.os }}-${{ github.run_id }}",
          })
          
          assert.deepStrictEqual(release.data.prerelease, true)
          assert.deepStrictEqual(release.data.body, "rofl lol test\nianal % fubar")
          assert.deepStrictEqual(release.data.assets[0].name, "TEST.md")
          const arraybuf = await github.request(release.data.assets[0].browser_download_url)
          const actual = Buffer.from(arraybuf.data).toString('utf8')
          console.log(typeof(actual))
          console.log(typeof(expected))
          assert.deepStrictEqual(expected, actual)

    - name: Make test promote
      uses: ./
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: README.md
        asset_name: TEST.md
        tag: ci-test-${{ matrix.os }}-${{ github.run_id }}
        overwrite: true
        promote: true
        prerelease: false
        make_latest: true
        body: "new body"

    - name: Check that the release is promoted
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        retries: 15
        script: |
          const fs = require('fs')
          const assert = require('assert').strict;
          
          const expected = fs.readFileSync("README.md", "utf8")
          const release = await github.rest.repos.getReleaseByTag({
            ...context.repo,
            tag: "ci-test-${{ matrix.os }}-${{ github.run_id }}",
          })
          assert.deepStrictEqual(release.data.prerelease, false)
          assert.deepStrictEqual(release.data.body, "new body")
          assert.deepStrictEqual(release.data.assets[0].name, "TEST.md")
          const arraybuf = await github.request(release.data.assets[0].browser_download_url)
          const actual = Buffer.from(arraybuf.data).toString('utf8')
          assert.deepStrictEqual(expected, actual)
          

    - name: Should fail uploading copy of the same file
      id: test-step
      if: matrix.os != 'windows-latest' # Bash-style if statements do not work on Windows
      uses: ./
      continue-on-error: true
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: README.md
        asset_name: TEST.md
        tag: ci-test-${{ matrix.os }}-${{ github.run_id }}
        body: "new body"

    - name: Verify failure occurred
      if: matrix.os != 'windows-latest' # Bash-style if statements do not work on Windows
      run: |
        if [ "${{ steps.test-step.outcome }}" == "failure" ]; then
          echo "Test passed - step failed as expected"
          exit 0
        else
          echo "Test failed - step should have failed but didn't"
          exit 1
        fi

    - name: Clean up
      if: ${{ always() }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const release = await github.rest.repos.getReleaseByTag({
            ...context.repo,
            tag: "ci-test-${{ matrix.os }}-${{ github.run_id }}",
          })
          await github.rest.repos.deleteRelease({
            ...context.repo,
            release_id: release.data.id,
          })
          await github.rest.git.deleteRef({
            ...context.repo,
            ref: "tags/ci-test-${{ matrix.os }}-${{ github.run_id }}",
          })
